#!/bin/sh /etc/rc.common
# Copyright (C) 2026 Shubham Vishwakarma <shubhamvis98@fossfrog.in>

START=99
STOP=10
USE_PROCD=1

start_service() {
	procd_open_instance
	procd_set_param command /usr/bin/ledmonitor
	procd_set_param respawn 3600 5 0
	procd_close_instance
}

stop_service() {
	return 0
}

